### ISSUE TITLE
Worn accessories disappear upon player death [during fight phases]

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#10]
Hats and other accessories worn by players disappear from view when they die until the next respawn. Is there anything that can be done to prevent this from happening?

**Comment by Donkie** [comment]
I thought I had code in place for this. Did this use to work?

**Comment by DawsonDevinity** [comment]
How far back are we referring to when the code was added?  From my recollection I've always seen worn accessory items disappear when player models are turned into ragdolls.

**Comment by Donkie** [comment]
Well the only relevant thing that could've broken it, if it existed, is the christmas update

**Comment by DawsonDevinity** [comment]
Approximately when was the code added (for a time estimate)?  It was added during the last six (6) months, I have not witnessed any change.

**Comment by Donkie** [comment]
It probably never existed.

**Comment by DawsonDevinity** [comment]
Alrighty, no problem.

**Comment by DawsonDevinity** [comment]
Needs to be looked into.

**Comment by Donkie** [comment]
Does this still happen in 2.0?
