### ISSUE TITLE
2.0 bugs

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#102]
List of bugs:

**CounterCraftz**
- [x] Obtained/Purchased Festive playermodels not appearing on store
- [x] Cannot sell tokens
- [x] huge watersplashes on new guns
- [x] 'secondary ammo' on golden gun
- [x] You can holster (and sell) default weapons
- [x] Old pistol/smg is still being given on fight phase for some reason
- [x] Tophat is '0 tokens' not sure if you can revert purchases from it since players have already bought this cosmetic
- [x] Sledge does 1 damage on pirate
- [x] Crowbar does 0 damage on pirate
- [x] !friends isn't working
- [x] juggs still has the old grenade
- [x] change us3's hostname and remove jailbreak from server list
- [x] bugbait has no ammo when redeemed on chest (pirate)
- [x] change slot list for pistol, 357 and ar2 (and theres 'secondary ammo' as well)
- [x] cannot purchase pig cosmetic
- [ ] this --> https://gyazo.com/bd423fda0e6d2d90984b1366ae5c50eb | i can hop on boats if player d/ced
- [x] Old weapons being given on One Weapon Event (possibly Randomized as well) - 8/24/16
- [ ] https://gyazo.com/df8773903573a19359a2eec1003f8813 this??????

**Dr. Pit Lazarus**
- [x] Everything is being reported as server TEST in logs

**Applcore5**
- [x] Colors on team round not showing up (props should be blue or red)
- [x] On Team Round, player's can't go on fellow teammates boats and plays as if were a normal round
- [x] Golden Gun won't aim, might have to do with secondary fire bug
- [x] Texture on hands missing when using rocket launcher
- [ ] Harpoon bounces all over the map when it hits a wall and doesn't reel you in
- [x] .0 appears at the end of vending machine health and possibly other props
- [ ] sledge can't do throw damage
- [x] Players not receiving compound bow
- [ ] Players joining team round don't get assigned to a team
- [x] Hands not showing up for revolver

**Dawson**
- [x] F1 function for recycling boats no longer works.
- [ ] Worn accessories disappear upon death.

**Comment by DrPitLazarus** [comment]
In the server logs, everything is being reported as server TEST.

**Comment by CounterCraftz** [comment]
crowbar does no prop damage on pirate

**Comment by CounterCraftz** [comment]
!friends isn't working

**Comment by CounterCraftz** [comment]
juggernauts gets the old grenade

**Comment by Applcore5** [comment]
- [ ] Colors on team round not showing up (props should be blue or red)

- [ ] Golden Gun won't aim, might have to do with secondary fire bug

- [ ] Texture on hands missing when using rocket launcher

**Comment by Applcore5** [comment]
- [ ] Harpoon bounces all over the map when it hits a wall and doesn't reel you in

**Comment by DrPitLazarus** [comment]
Why'd you assign me for?

**Comment by CounterCraftz** [comment]
so i can add you as participant

**Comment by Applcore5** [comment]
What does the assigning do?

**Comment by Donkie** [comment]
The disconnect no pushoff one is abit tricky
Teams are not known for a disconnected player. Thus if you build a boat for your team, disconnect, your entire team would be pushed off.

**Comment by DawsonDevinity** [comment]
Two things:

- F1 function for recycling boats no longer works.
-  Worn accessories disappear upon death.

**Comment by Donkie** [comment]
Closing this, if any issue is still relevant, make separate issues.
