### ISSUE TITLE
F1 function is no longer operative

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#105]
Boats can no longer be "recycled" for future rounds.  Pressing F1 as soon as the Battle phase ends fails to work.

**Comment by Donkie** [comment]
I'd like more sources on this since it seems like such a wide feature that it'd be noticed earlier

**Comment by DecapX** [comment]
I noticed this last night however I was on the event server (along with Dawson) and assumed it was because the event that was coming up did not allow saving boats. I have not checked this on a normal server.

**Comment by Donkie** [comment]
Yeah that is a thing.

**Comment by Applcore5** [comment]
Tested this and isn't working on normal rounds.

**Comment by Donkie** [comment]
Fixed
