### ISSUE TITLE
Teams are fucked up?

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#106]
http://images.akamai.steamusercontent.com/ugc/263845944680820083/66F78438675FDA0FE5FDCC5F81FB7B090C77B73B/

**Comment by Applcore5** [comment]
This was in my 2.0 bugs list

**Comment by Donkie** [comment]
Might be fixed with the last team update, reopen if not.

**Comment by CounterCraftz** [comment]
https://i.gyazo.com/a7c9219c43b7c9e08162547f3b891cf2.jpg

**Comment by Donkie** [comment]
rip

**Comment by CounterCraftz** [comment]
http://pastebin.com/d6LvP9WX

**Comment by CounterCraftz** [comment]
http://pastebin.com/b4PkbV08

**Comment by Donkie** [comment]
I also need some idea on what's wrong, what's expected
