### ISSUE TITLE
Couldn't find model definitions for doctor model

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#11]
[ERROR] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/entities/entities/fm_hat/cl_init.lua:58: Couldn't find model in definitions "models/player/11thdoctor/thedoctor.mdl"
  1. error - [C]:-1
   2. unknown - gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/entities/entities/fm_hat/cl_init.lua:58

When server about to restart, script error. Happened around when you added snowman and queued to restart.

Probably has to do with "The Doctor" PM.

**Comment by Donkie** [comment]
Welcome to github!
In the future, one issue per issue please.
I've also already fixed the "You already own this!" bug.

**Comment by CounterCraftz** [comment]
k

**Comment by Donkie** [comment]
fixed
