### ISSUE TITLE
New Forum Trophies

### ISSUE THREAD

**Issue by Applcore5** [GMDevinity/Flood#110]
There was a thread awhile back, created by Decap thats long since been forgotten. This is the list containing some of the suggested trophies.  

Good Stuff - 5 points - give out 25 likes
Impressive - 10 points - give out 50 likes
Funny Guy - 5 points - get rated 'Funny' 25 times
Class Clown - 10 points - get rated 'Funny' 50 times
The Comedian - 20 points - get rated 'Funny" 100 times
Smart Guy - 5 points - get rated 'Informative' 25 times
NEERRD! - 10 points - get rated 'Informative' 50 times
The Scientist - 20 points - get rated 'Informative' 100 times
D'aww! - 5 points - get rated 'D'aww" 25 times
Kawaii - 10 points - get rates D'aww' 50 times
The Doll - 25 points - get rated 'D'aww' 100 times
Superstar - 15 points - Obtain 300 comments on your profile
Unemployed - 10 points- Log into forums once a day for 31 days
Public Speaker - 10 points - Create 50 threads

**Comment by Donkie** [comment]
the reason it was forgotten was because of the difficulty to implement any of these.

**Comment by jeffreythe00** [comment]
Ditto what Donkie said + not enough people really use the forums as is. So if Donkie is going to spend his time coding. I'd rather it be for some big juicy update on flood, where it will receive the most attention.

**Comment by jeffreythe00** [comment]
If this becomes a relevant topic in the future, feel free to reopen it. Going to close it because I feel it is near the bottom of the "to do" list unless @bayrock wants to take a crack at it. (Really up to him though)
