### ISSUE TITLE
Everything devinity died

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#114]
Everything died at about 2AM EST. Website and flood went offline for about 10 mins and then came back online, laggy as hell but somewhat working. Servers didn't start properly, needed to be hard stopped and started.

**Comment by jeffreythe00** [comment]
@Donkie just incase it threw out some kind of error.

**Comment by Donkie** [comment]
It was a scheduled NFO restart, a disk crashed at the same time aswell
causing the slowdown. It'll be resolved automatically soon.

**Comment by jeffreythe00** [comment]
Awesome! Thanks for the update!

**Comment by jeffreythe00** [comment]
Also, creds to laz for telling me :dango:
