### ISSUE TITLE
Can not sell tokens

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#119]
Players can not sell their tokens. No error message or anything.

**Comment by bayrock** [comment]
The way Jeff worded this confused me, but I think what he means is you can't buy flood cash in the store?

**Comment by jeffreythe00** [comment]
Correct

**Comment by jeffreythe00** [comment]
I'm getting a lot of complaints for this and the combat bow issue. Will this be fixed by the next update?
