### ISSUE TITLE
Player bans do not go in effect whilst the player banned is in the server.

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#12]
Title. Roflcopter Rogers told me that if the player is still on and I ban him via BanCP, it doesn't get carried.

**Comment by CounterCraftz** [comment]
I have to kick him on the server to make the ban go in affect.

**Comment by Donkie** [comment]
I've looked in the code and can confirm this would happen, I'll look into fixing it!

**Comment by Donkie** [comment]
Fixed!
