### ISSUE TITLE
One weapon event - no ammo on grenade

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#121]
https://i.gyazo.com/17914d3ae1969a5c427c89fd26ac01b0.png
Never tell your password to anyone.
11:52 PM - Seboo23_: How to skip round sir
11:53 PM - CounterCraftz: you cant
11:52 PM - Seboo23_: Oh..
11:53 PM - CounterCraftz: just vote to skip phase for now
11:53 PM - Seboo23_: Yeah thats what I meant
11:53 PM - Seboo23_: how
11:54 PM - CounterCraftz: Q>Vote
11:54 PM - CounterCraftz: what event
11:54 PM - CounterCraftz: one weapon?
11:53 PM - Seboo23_: one weapon grenade
11:53 PM - Seboo23_: still cant find it
11:53 PM - Seboo23_: found it
11:53 PM - Seboo23_: skipping
11:53 PM - Seboo23_: Thanks

**Comment by Donkie** [comment]
Fixed
