### ISSUE TITLE
Optimization question

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#122]
So, one of the recent GMOD updates enables the use of multicore rendering. 

Following (this guide - http://chronet.com/threads/how-to-enable-multicore-rendering-in-gmod-improve-your-fps.7655/ ) I am able to get 170+ FPS on a local server. On Devinity flood, I am only able to get 20-70 FPS. 

My question is, if we added those cfg files to the server, would they allow me to gain FPS and would people be able to toggle them?

![2016-09-23_10-58-50](https://cloud.githubusercontent.com/assets/6297372/18790695/be766dbc-817d-11e6-832e-ac578b124afc.jpg)
![2016-09-23_10-58-03](https://cloud.githubusercontent.com/assets/6297372/18790700/c27f04be-817d-11e6-88a5-51f0b134d9d9.jpg)

**Comment by Donkie** [comment]
It's convars for the client. The server shouldn't change them. 
The reason they're disabled by default is that it isn't very tested and might break gmod.

**Comment by jeffreythe00** [comment]
Ok, makes sense. Was just curious is all. 

Thanks,
Jedf
