### ISSUE TITLE
Allow Jr Mod+ to remove disconnected props

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#126]
_Jr Mod and Mod should have the ability to remove a players prop if they are disconnected. This would prevent them from abusing prop removal. (Currently only admin+ can remove any kind of prop.)_

**If player has disconnected**
- Allow Jr Mod+ to delete a players prop
- Allow Jr Mod+ to use (C+Right click+Delete) 

It is useful because, they would be required to issue a warning before they kick a player. They can then proceed to remove any prop that may have been causing issues.

**Example 1**

Player 1 freezes a prop on Player 2's boat.
Mod kicks/bans Player 1 for sabotage
Mod can now help Player 2 by deleting the frozen prop

**Example 2** _(Use of C+Right click+delete)_

Reflect phase happens, to start fight phase, Player 1's boat glitches and starts sharking.
Mod kicks/bans Player 1 for glitched boat
Mod can now delete the boat even though he does not have access to his toolgun

**Comment by Donkie** [comment]
Wouldn't it just be better that props were cleaned up if the owner was kicked/banned?

**Comment by jeffreythe00** [comment]
Yes it would work. However, that means if you kicked me for mic spam, I would automatically lose my entire boat. 

Thats the only downside I can think of. If that if fine with you, then its fine with me.

**Comment by Donkie** [comment]
if you micspam you're a dick, you deserve your boat to get ruined

**Comment by jeffreythe00** [comment]
Funniest thing I have heard in a while. Delete boat on kick it is then :p
