### ISSUE TITLE
Forum suggestion - trash bin

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#127]
We could really use a trash bin on the forum. This way,  forumsmods could move deleted threads to here and we would be keeping the forum tidy. (The "trash bin" is similar to the golden threads)

**Comment by Applcore5** [comment]
I don't see why not, it'd be an easy way to find deleted items. +support

**Comment by jeffreythe00** [comment]
I forgot about this thread actually. I'll make a trash can as soon as I get back from chores

**Comment by jeffreythe00** [comment]
Added a **Deleted Threads** sub-forum under the **Mod Forum**
