### ISSUE TITLE
A few errors

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#128]
@Donkie 

I don't know if these errors are relevant or not but I wanted to at least bring them up.

US 1 crashed (and has been crashing frequently). So I wanted to see if I could find out why. Here are some of the last lines in the log before it crashed. 
http://f.devinity.org/V4SOcd

Also I found this error in console log when starting US 1. (Don't know if that has anything to do with the combat bow or not)

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.

**Comment by Donkie** [comment]
The errors in the images are just leftover crap and doesn't affect anything
````[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.```` is expected

Thanks for bringing this up though!
