### ISSUE TITLE
New Weapon Additions, Replacements, and Updates

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#13]
Created a doc. sheet for storing ideas for new weapon additions, replacements, and updates.

https://docs.google.com/document/d/1kOb5LwW-1IBFDEo2OwAp6qYxmrGMJjjxP_fUuOWgEFk/edit?usp=sharing

Let me know what could work and what can be scrapped.

**Comment by CounterCraftz** [comment]
I think the FN FAL should be re-worked since galil could easily beat the gun just how time consuming by its rate of fire. It is indeed a great weapon but I think the damage needs to increase probably by 1-2.5 since it is slightly related to the AR2 as well as decreasing the cone by a small amount.

**Comment by Donkie** [comment]
Great work, will definitely use this.

However your accuracy, rate of fire, reload speed values are pretty much useless to me. I'll give you a list of these values on our current weapons.

**Comment by CounterCraftz** [comment]
Sorry to pitch in like this but: https://steamcommunity.com/sharedfiles/filedetails/?id=254112908

Could be great for those who want to give someone a beating. Would probably unweld each prop with a ratio of 50:50. Probably 25 damage per hit? It only takes a few seconds to swing the sledgehammer unlike the crowbar.

**Comment by Donkie** [comment]
-	AWP	-
    RateOfFire:	1.3
    Recoil:		2
    Cone:		0
    -	Famas	-
    RateOfFire:	0.075
    Recoil:		0.4
    Cone:		0.015
    -	TMP	-
    RateOfFire:	0.06
    Recoil:		0.4
    Cone:		0.04
    -	Five Seven	-
    RateOfFire:	0.15
    Recoil:		1.2
    Cone:		0.02
    -	Desert Eagle	-
    RateOfFire:	0.3
    Recoil:		2.5
    Cone:		0.02
    -	M249	-
    RateOfFire:	0.09
    Recoil:		2
    Cone:		0.05
    -	AK-47	-
    RateOfFire:	0.07
    Recoil:		1.5
    Cone:		0.02
    -	SVU	-
    RateOfFire:	0.15
    Recoil:		2
    Cone:		0
    -	Galil	-
    RateOfFire:	0.09
    Recoil:		0.65
    Cone:		0.017
    -	M16	-
    RateOfFire:	0.1
    Recoil:		1
    Cone:		0.02

**Comment by Donkie** [comment]
Rate of fire is the delay in seconds between each shot
Recoil is some kind of multiplier to how much the screen will get nudged
Cone is roughly the diameter of the "shoot cone", higher cone = more spread

Reloadspeed is never defined as a number, rather just how long the animation is.

**Comment by DawsonDevinity** [comment]
Ah, those values will come in handy–I'll rework stats based off of what you provided.  Thanks for clearing that up.
_____________________

I created a weapon spreadsheet some time ago, but it lacks information concerning the above.  Should the above weapon values remain confidential or are they safe to display outside of Github?

**Comment by DawsonDevinity** [comment]
The document has been updated.
_________________________________
Changes:
1) Added five (5) new weapon ideas
2) Added one (1) new weapon update

**Comment by DawsonDevinity** [comment]
All of Decap's weapon ideas have been added to the document.  The new weapon count is now up to 25.

**Comment by Donkie** [comment]
To answer your question, keep the values here on github.

**Comment by DawsonDevinity** [comment]
Will do.  They have remained un-plastered elsewhere since I first asked.

**Comment by Donkie** [comment]
What's the point of the "Invisible Camouflage" weapon? Why would you want to be visible

**Comment by DawsonDevinity** [comment]
Not sure.  Perhaps to remain more inconspicuous.  ...But, it 'twas Decap's idea.

**Comment by DecapX** [comment]
@Donkie I'll be sending Dawson some updates to my weapon suggestions which he will add to his doc

**Comment by DecapX** [comment]
Bump, are any more weapons from this being considered? @Donkie

**Comment by Donkie** [comment]
Whenever I'm in the mood to code weapons and I got time for it I'll consider it, you don't need to bump this. 

I'm stoked with items update and mapping atm

**Comment by DawsonDevinity** [comment]
That's fine.  Once we're in a comfortable position with the aforementioned, we can turn our attention to moar weapons.

**Comment by CounterCraftz** [comment]
Flood 2.0 cough

**Comment by DawsonDevinity** [comment]
Added the following weapons:

(1) Disintegrator
(2) Interceptor
