### ISSUE TITLE
New props are ready to be added to servers + considerations

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#138]
I am pleased to announce that all of the new props have been assigned proper stat values and should be ready for implementation into the servers.  For your and everyone's convenience a copy of my [finalized...] prop spreadsheet work will be attached to this issue for download + reference. 

All prop models can be found here:  
- http://steamcommunity.com/sharedfiles/filedetails/?id=774891921

____________________
While several of the new props are planned to have special attributes, some may remain as mundane for now.  With that said, I would like to see if we could configure the following props to act accordingly prior to release:

(1) **Vending Machine (Types A, B, C)**
- Configure all three types so that they share the same 2-spawn limit.

(2) **Playground Structure**
- Configure so that spawning one in counts as four (4) props toward max prop limit.

(3) **Iceberg** (?)
- Configure so that prop begins losing 1 HP per second as soon as Battle Phase kick in.

(4) **Explosive Drum**
- Configure so that prop explodes when destroyed.  Explosions inflict prop damage, regardless of ownership.

(5) **Biohazard Drum**
- Configure so that prop releases bugbait gas when destroyed.

_____________________
If we cannot be bothered to meddle with the above for now, the Vending Machine variants and the Playground Set may be temporarily removed from the prop list until the above configs. have been devised.

[Devinity Flood Prop Config Final.xlsx](https://github.com/GMDevinity/Flood/files/541300/Devinity.Flood.Prop.Config.Final.xlsx)

**Comment by Donkie** [comment]
I spoke with Counter about directly adding that workshop addon to our server. That way you guys can add new models as you see fit, and you can then add the database rows when you've finished testing.

**Comment by DawsonDevinity** [comment]
Nice, so that means I can add rows once we add the server pack?  Previously I thought I lacked the permissions to do so.
