### ISSUE TITLE
Decrease sprint speed while swimming

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#139]
Title speaks for itself.  The decrease could be something reasonable (25%*).  There should be some kind of ramification for building a boat far away from opponents + scattering mini boats too broadly from each other; the players aren't and shouldn't be Michael Phelps.

___________________________

*I was tweaking with the _Simple Player Speeds Changer_ workshop addon and saw that the following values are set by default:
- Walk speed ........... 250
- Run speed ............. 500

Adjusting the run speed to 375 seems to work out well enough.  Not too fast, but not too slow, either.

http://steamcommunity.com/sharedfiles/filedetails/?id=636573283&searchtext=swim+speed

**Comment by DawsonDevinity** [comment]
Secondarily, slower running speeds would also help out with moderation in that rule-breakers would be easier to catch + scoop up with the Physics Gun.

**Comment by Donkie** [comment]
correction: we currently have 250 walk and 400 run speed on servers.

**Comment by DawsonDevinity** [comment]
Ah....  Well, we could still try adjusting the run speed to 375 and see how that works.

**Comment by Donkie** [comment]
Decreased to 150/300, try it out yo

**Comment by DawsonDevinity** [comment]
We'll need one of our compadres to test that since I've got everything installed.  If the speeds are too sluggish they can be bumped up slightly by whatever degree they think would be appropriate.
