### ISSUE TITLE
Ability to ban multiple SteamIDS in BansCP

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#14]
Not an issue but a mere/minor suggestion. Would be easier if you could ban multiple players just by adding a comma in between. 
(E.G. https://gyazo.com/e4614e0a4303eb8ff38f5137f75107fa )

**Comment by Donkie** [comment]
:+1:

**Comment by DawsonDevinity** [comment]
W

**Comment by Donkie** [comment]
Added

**Comment by CounterCraftz** [comment]
Can you add some type of info on the banspage? I completely forgot that this even existed.

**Comment by Donkie** [comment]
good idea

**Comment by Donkie** [comment]
Done
