### ISSUE TITLE
[Database] Increasing max Buoyancy range from 1 to 5

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#140]
I'd like to see if we could edit the value input range for Buoyancy.  I find that the heavier a prop is, the less effective buoyancy will become unless its own value is made to scale accordingly.

**Comment by Donkie** [comment]
not sure what this means. The buoyancy is a decimal value between 0 and 1, that's how it works in the engine.

**Comment by DawsonDevinity** [comment]
Yeah, I was interested in finding out if that range from 0 to 1 could be changed to 0 to 4.

**Comment by Donkie** [comment]
But there's no point, if you put in 4 it would just be divided to 1 ingame, if you put in 3 it would be divided to 0.75.

Just put in decimal values directly
