### ISSUE TITLE
!cake Anti-Cheat randomly kicking players & bans don't show up on banspage

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#141]
https://slack-imgs.com/?c=1&o1=wi385.he165&url=https%3A%2F%2Fbot.gyazo.com%2F1207d68398f9b38c40589a5da2097983.png

https://slack-imgs.com/?c=1&o1=wi338.he332&url=https%3A%2F%2Fbot.gyazo.com%2F0ca5371c106674d915362e413b30bc0f.png

@Donkie

**Comment by DawsonDevinity** [comment]
Short story: The "Supreme9000" needs to be euthanized, asap.

**Comment by Donkie** [comment]
I'm confused

**Comment by Donkie** [comment]
Also can't you guys edit settings

**Comment by Donkie** [comment]
+cac_menu

**Comment by jeffreythe00** [comment]
Came home from work. US1 and US3 were offline. Started up both just fine. 

Can't open 
+cac_menu (Unknown command: +cac_menu)


Found this error on US1 - Same error on US 3

Couldn't include file 'extensions\client\vehicle.lua' (File not found) (@addons/cac-release-20161011/lua/includes/init.lua (line 263))

**Comment by bayrock** [comment]
I don't see anything suspicious going an right now. Maybe Donk knows about the cake issue.

**Comment by jeffreythe00** [comment]
I've shut down the US servers temporarily until the issue is resolved. Theres no reason to have then up if nobody plays

**Comment by Donkie** [comment]
I updated the anti cheat, maybe the upload half-failed on the US servers. I'll retry uploading
