### ISSUE TITLE
Body Bag + Great White + Restraint Bed props do not ragdoll when spawned

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#142]
Earlier today we added several props that are technically ragdolls.  Once spawned, however, they observed to be as stiff as plywood.  CounterCraftz mentioned that some kind of column could be added to the config page that would allow for applicable props to assume ragdoll behavior if enabled.

Hopefully something could be done to remedy the issue.  Those props have since been taken out of the config.

**Comment by Donkie** [comment]
Probably not, a lot of code have to be rewritten to account for that I'm afraid.

**Comment by DawsonDevinity** [comment]
Flood's code can't even account for ragdolls?  : /  Well shit, that's a letdown.

**Comment by Donkie** [comment]
We've never had them before so it hasn't really been any priority.

**Comment by Donkie** [comment]
We've never had them before so it hasn't really been any priority.

Den 23 okt. 2016 12:37 em skrev "Dawson" <notifications@github.com>:

**Comment by DawsonDevinity** [comment]
Closing issue.  If there ever comes a time when we consider optimizing Flood's code, hopefully ragdolls will one day be made compatible.
