### ISSUE TITLE
Some LUA errors

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#143]
@Donkie 

Got these errors upon joining US 2. 

[ERROR] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/cl_score.lua:207: SpawnableProps(models/props_phx/construct/wood/wood_panel2x2.mdl) is nil!
1. error - [C]:-1
   1. unknown - gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/cl_score.lua:207

Timer Failed! [PropDataGathererForScoreboard][@gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/cl_score.lua (line 175)]

**Comment by jeffreythe00** [comment]
Directly after a juggernaught event. EU 1

Error in hook OnPlayerChat: gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/cl_voice.lua:236: bad argument #1 to 'find' (string expected, got nil)
stack traceback:
	[C]: in function 'find'
	gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/cl_voice.lua:236: in function <gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/cl_voice.lua:200>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

**Comment by Donkie** [comment]
First one is because you're missing content probably.
Second one will be fixed

Thanks for reporting!
