### ISSUE TITLE
Staff app plugin is down

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#147]
@Donkie 

People can't apply for staff. When they submit the application, it fails and throws this error. Therefore wasting ALL of their time. I gave the guy who informed me about this 20 tokens because I felt bad that he spent all that time and lost all of it.

Prepare failed: (1142) INSERT command denied to user 'devinity'@'localhost' for table 'xf_thread'

DBStmt() in StaffApp/main.php at line 261
StaffApp_main::MakeThread() in StaffApp/main.php at line 246
StaffApp_main::ParseInput() in StaffApp/main.php at line 418
StaffApp_main::includeFile()
call_user_func_array() in XenForo/ControllerPublic/Page.php at line 46
XenForo_ControllerPublic_Page->actionIndex() in XenForo/FrontController.php at line 351
XenForo_FrontController->dispatch() in XenForo/FrontController.php at line 134
XenForo_FrontController->run() in /var/www/devinity.org/public_html/index.php at line 13

**Comment by Donkie** [comment]
Fixed.

Also recoded it abit so now it will properly give emails if you've subscribed to the forum etc.

**Comment by jeffreythe00** [comment]
Admin app creation error
Please notify Devinity staff about this:
Array ( [error] => 7 [message] => Something went wrong when "creating a new thread": "The user does not have permissions to post in this thread" [user_error_id] => 14 [user_error_field] => [user_error_key] => general_user_thread_creation_error [user_error_phrase] => The user does not have permissions to create a new thread in this forum. )

**Comment by Donkie** [comment]
Fuq

**Comment by Donkie** [comment]
Attempted fix, can anyone help me test this with a user that doesn't have permission to post in the staff app forum?

**Comment by CounterCraftz** [comment]
https://gyazo.com/2cb483590ddd20983927a06cfb8f7cb0

logged in w/ alt https://gyazo.com/c0e59cc5dff9778b44ea3246cd892922
external account already linked

**Comment by CounterCraftz** [comment]
@Donkie
