### ISSUE TITLE
Latest Member bug

### ISSUE THREAD

**Issue by Applcore5** [GMDevinity/Flood#148]
Latest member doesn't seem to be updating on forums. says the latest  member was October 13th but I've seen plenty of players who have signed up later than that.

**Comment by CounterCraftz** [comment]
I've tagged Donkie a couple of times about this, forum registration is disabled when signing up through steam

**Comment by CounterCraftz** [comment]
Never mind he just fixed

**Comment by CounterCraftz** [comment]
Yeah its been fixed, check latest member
