### ISSUE TITLE
Additions to song list

### ISSUE THREAD

**Issue by DecapX** [GMDevinity/Flood#15]
A few additions that should be made to the current song list.
- [ ] Multiple filters should be able to be ticked, currently you can only select one.
- [x] Add "Uploaded By" filter option or preferably a whole new tab to select an uploader and view all song uploaded by that person. 
- [x] Add sorting option of song duration.
- [x] Delete song command (only for songs you have uploaded)
- [x] Add display option "Ascending-Descending/Descending-Ascending" to our current options of "A-Z/Z-A" 
- [x] Add a counter of how many current songs are listed. Start with the default when it's first brought up. Then after filters have been applied it can show how many songs are displayed with those filters.
- [ ] I would love to be able to add certain songs to be played in specific events. I remember Donkie saying that would be a lot of work though.

**Comment by DawsonDevinity** [comment]
How about a feature that prevents people from adding more songs after the 300-count is hit?  This will prevent an accidental wipe out of the entire song list.

**Comment by Donkie** [comment]
The last Wipeout wasn't "accidental"

**Comment by DawsonDevinity** [comment]
Well, my point still stands.

**Comment by DecapX** [comment]
Didn't Donkie remove the 300 limit issue?

Anyway I've updated the wording a little better and added a few more suggestions.

**Comment by DawsonDevinity** [comment]
Donkie, please verify whether or not the 300-song limit has been removed.

**Comment by Donkie** [comment]
It's still there.

**Comment by Donkie** [comment]
Also there is already a remove song command, albeit it's "hidden".

!removesong <title>

**Comment by DawsonDevinity** [comment]
I'll do a recount of all the songs we currently have when time is made available.  After everything's been recorded I can create a public thread for garnering feedback from users (e.g., are there any songs that aren't fitting?  Any that aren't working?  Etc.).
