### ISSUE TITLE
halloween models

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#154]
http://f.devinity.org/TORlYx
mdl and token price below post

Cauldron Entity (for deco, content required is already in the pack except for .lua file)
edited lua file (got rid of sounds)
https://slack-files.com/T0H7GJL7Q-F2VQN5B3N-5c3008ec6b

**Comment by CounterCraftz** [comment]
added omega jugg to content (there are 2 variants now)
models/humans/agnt/juggernaut.mdl
arms: models/weapons/c_arms_combine.mdl (not sure about the path)

**Comment by CounterCraftz** [comment]
Oogie: models/oogieboogie.mdl | 75 tokens;Holiday Exclusive

Omega Juggernaut: models/humans/agnt/juggernaut.mdl | 175 tokens
c_arms: models/weapons/c_arms_combine.mdl

Juggernaut: models/juggerjaut_player.mdl | 100 tokens
c_arms: models/weapons/c_arms_combine.mdl

Rotten Miku: models/captainbigbutt/vocaloid/miku_rotten.mdl | 175 tokens;Holiday Exclusive
c_arms: models/captainbigbutt/vocaloid/c_arms/miku_rotten.mdl

Manny Calavera: models/doktor_haus/manny.mdl | 50 tokens;Holiday Exclusive
c_arms: models/doktor_haus/manny_arms.mdl

**Comment by Donkie** [comment]
Realised we probably need to hat position these... the system isn't really ready for new pms yet :(

**Comment by CounterCraftz** [comment]
Rip

**Comment by CounterCraftz** [comment]
so 2015 halloween assets are being used correct? new plymdls cannot be added later on in the event?

**Comment by DawsonDevinity** [comment]
Dude, just add the bloody player models.  They will be assigned hat positioning as we move along.

**Comment by CounterCraftz** [comment]
In regards with devpos tool, new player mode refuses to work dunno if I've already said it before.

**Comment by Donkie** [comment]
yeah you've said it and I've ignored it because it's probably gonna be remade soon anyways.
