### ISSUE TITLE
New props are errors

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#157]
I noticed for some reason that I was unsubbed from the Flood materials and community content. Other players are reporting hgis as well.

**Comment by CounterCraftz** [comment]
probably needs full server restart, i've updated content for halloween prep

**Comment by DawsonDevinity** [comment]
The ****?  I hope the restart works.

**Comment by jeffreythe00** [comment]
This has been an issue since yesterday at least. It will be OK Dawson. Don't worry

**Comment by CounterCraftz** [comment]
Yeah most likely content update

**Comment by CounterCraftz** [comment]
I've restarted the servers 3-5 mins ago, can someone w/o content go and check?

**Comment by CounterCraftz** [comment]
I'm assuming it's been fixed.
