### ISSUE TITLE
Some YouTube songs cannot be added to the songlist

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#16]
For certain songs that are on YouTube (E.g. Summer Samba, Mona Lisa Overdrive V2), attempts to add them lead to the following error being displayed:

"Download error, check logfile"

When entered via console, an error stating "Title needs to be at least 3 characters" also appears, even though the desired song's name has more characters than that. Please note that the above happens with different videos that play the same song.

Any hypothesis for what might be going on?

---

Summer Samba (https://www.youtube.com/watch?v=VGNwXq6vPoI)
Mona Lisa Overdrive V2 (https://www.youtube.com/watch?v=2fp8mYC5abE)

**Comment by DecapX** [comment]
Are you trying to add it via the menu or have you tried the text option as well?

**Comment by DawsonDevinity** [comment]
I've done both.

**Comment by Donkie** [comment]
This is weird shit and I can't reliably reproduce it, nor know what's wrong. There is errors in the logs but they don't really tell me anything.

When this happens, I suggest waiting a few days and try again, or just skip this song.

**Comment by DawsonDevinity** [comment]
I haven't done it in a while.  Could give it another shot.
