### ISSUE TITLE
Paper towel - Incorrect display info.

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#163]
@DawsonDevinity @Donkie  @bayrock 

This guy http://devinity.org/members/frozen%E2%99%A1humanity.535/ noted that don't have a limit on the paper towels. It would be more informative to the player if we added "**None**" or "**∞**" (and I tend to agree)

Thanks in advance!

**Comment by CounterCraftz** [comment]
Should we add a limit then? I thought it'd be pretty obvious 😕

**Comment by jeffreythe00** [comment]
Maybe make the limit say 16? Not a huge deal IMO.

**Comment by Donkie** [comment]
Done
