### ISSUE TITLE
Severe issue – Build Phase does not start

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#165]
@Donkie 

There is a bug where, after a juggernaught round. The build phase does not start. Everyone who is dead will remain dead, and anyone living can do as they please. This **really** needs to be fixed because I had to restart the server just to fix it. 

I'm down for troubleshooting whenever you have time.

**Comment by jeffreythe00** [comment]
I triggered a juggernaught round to see if it would happen again. Didn't seem to but watching the console closely... Soon as the fight phase ended this was happening. (Taken from console on ServerCP)

`[game] Changed phase to Reflect
[^_^|590|STEAM_0:0:113509693] Lua Error:
[EngineSpew error] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/sv_enginespew.lua:31: attempt to index local 'err' (a nil value)
Trying to remove server entity on client!
[^_^|590|STEAM_0:0:113509693] Lua Error:
Trying to remove server entity on client!
[EngineSpew error] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/sv_enginespew.lua:31: attempt to index local 'err' (a nil value)
[^_^|590|STEAM_0:0:113509693] Lua Error:
Trying to remove server entity on client!
[JazzyEmu|593|STEAM_0:0:30493941] Lua Error:
Trying to remove server entity on client!
[EngineSpew error] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/sv_enginespew.lua:31: attempt to index local 'err' (a nil value)
[JazzyEmu|593|STEAM_0:0:30493941] Lua Error:
Trying to remove server entity on client!
[JazzyEmu|593|STEAM_0:0:30493941] Lua Error:
Trying to remove server entity on client!
[EngineSpew error] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/sv_enginespew.lua:31: attempt to index local 'err' (a nil value)
[Cellnor|594|STEAM_0:0:28538411] Lua Error:
Trying to remove server entity on client!
[Cellnor|594|STEAM_0:0:28538411] Lua Error:
Trying to remove server entity on client!
[Cellnor|594|STEAM_0:0:28538411] Lua Error:
Trying to remove server entity on client!
[EngineSpew error] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/sv_enginespew.lua:31: attempt to index local 'err' (a nil value)
[CookieManiakHD|598|STEAM_0:0:64963137] Lua Error:
Trying to remove server entity on client!
[CookieManiakHD|598|STEAM_0:0:64963137] Lua Error:
Trying to remove server entity on client!
[CookieManiakHD|598|STEAM_0:0:64963137] Lua Error:
Trying to remove server entity on client!
[EngineSpew error] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/sv_enginespew.lua:31: attempt to index local 'err' (a nil value)
[[pink]Jeffrey[lime]the00|601|STEAM_0:0:29495527] Lua Error:
Trying to remove server entity on client!
[[pink]Jeffrey[lime]the00|601|STEAM_0:0:29495527] Lua Error:
[EngineSpew error] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/sv_enginespew.lua:31: attempt to index local 'err' (a nil value)
Trying to remove server entity on client!
[[pink]Jeffrey[lime]the00|601|STEAM_0:0:29495527] Lua Error:
Trying to remove server entity on client!
[EngineSpew error] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/sv_enginespew.lua:31: attempt to index local 'err' (a nil value)`

**Comment by Donkie** [comment]
Those errors are irrelevant for this. I tried this in my local server and idk what causes it.
