### ISSUE TITLE
Song list issue

### ISSUE THREAD

**Issue by Kolser** [GMDevinity/Flood#167]
During the "Battle Phase," songs won't start or the "Building Phase" songs play instead.
[Evidence](https://www.youtube.com/watch?v=nQ3N_91O0tw)

**Comment by Donkie** [comment]
Not sure what the video is supposed to show other than a funky tune playing.

I've tested this in my local server and it seems to work as intended. You sure it wasn't just somebody force playing that song?

**Comment by CounterCraftz** [comment]
'hotel' starts playing during fight for some reason eventhough halloween songs are currently whitelisted (and no, no one force played that song)

**Comment by Donkie** [comment]
ah yeah, funny one that, someone added another hotel song, there's two

**Comment by Donkie** [comment]
Fixed then I guess
