### ISSUE TITLE
Having a "Battle Phase" gun instead of your Phys-Gun/Tool-Gun

### ISSUE THREAD

**Issue by Kolser** [GMDevinity/Flood#168]
You can't use your Phys-gun or Tool-gun if this happens. You'll keep shooting from your "Battle Phase" weapon if you hold down Mouse1. This gives visual and sound effects. Also, other players can't see your current weapon. They'll only see you holding your Phys-gun/Tool-gun.
[Evidence](http://images.akamai.steamusercontent.com/ugc/367434986781237598/2B8D35D0C31D7FF49C03A5D178FDC492839962A5/)

**Comment by CounterCraftz** [comment]
Usually clientside glitch, try killing yourself (ingame)

**Comment by Donkie** [comment]
I like that you totally ignored the bug template.

I can't recreate this at all

**Comment by CounterCraftz** [comment]
yeah this bug can't be replicated, 75% sure think it has something to do with thirdperson
