### ISSUE TITLE
Purchasing and equipping Jack doesn't give achievement

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#169]
[//]: # (----Bug Template Info Start----)
[//]: # (Remove this section before posting. Remove this entire template if you're not reporting a bug)
[//]: # (!!!!Gather as much evidence as you can. There will often be a lua error somewhere,)
[//]: # (either in your console or in the server console, which can be reached using the ServerCP)
[//]: # (----Bug Template Info End----)

### Description of bug
Purchasing and equipping Jack Skellington doesn't give player holiday achievement (Masquerade)

### What I expected to happen
for achievement to work

### What instead happened
doesn't work

### Steps to reproduce
* purchase jack
* equip jack
* ???

### Extra info (evidence, logs, etc)
https://i.gyazo.com/28e4fdb778887346382bb36ce1bcc7cc.png
player currently in screenshot equipped jack

**Comment by Donkie** [comment]
rip, code was lost in the making of items 2.0
