### ISSUE TITLE
Weapon inventory update for Juggernauts

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#171]
Thought we could edit the Juggernaut weapon inventory so that it may include the following:
- Minigun
- Sticky Bombs
- Frag Grenades
- FiveSeven

______________________

The Minigun could be designated as a Juggernaut-exclusive weapon, where it may have the following stats:
- Damage ............................... -5 HP
- Magazine + Reserve ............ 150 + 300

The fire rate is much faster than the M249.  As a matter of fact, the Minigun could be made to replace it entirely.

_______________________

**Link to Minigun swep:**
- http://steamcommunity.com/sharedfiles/filedetails/?id=338915940

**Comment by jeffreythe00** [comment]
I've always wanted to see a minigun added to flood but couldn't "really" justify it under normal circumstances. I do however think juggernaut round would be a good place for it though if done properly

**Comment by Donkie** [comment]
Minigun would be a cool af weapon but boring to only give it to a few people during a low chance event. Anywhere we could make it appear aswell?

**Comment by bayrock** [comment]
The ability to mount a turret or 'minigun' to a boat might be rad.

**Comment by Donkie** [comment]
That wouldn't be a handheld weapon tho.

**Comment by DawsonDevinity** [comment]
@bayrock:  I have an idea for an emplacement turret tool that can be considered.

@Donkie:  Could be a "Death Machine" sort of weapon that has limited ammunition and can be "rented" out during conventional matches for a modest fee.
