### ISSUE TITLE
[WEAPON ADDITIONS] Shotguns

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#178]
http://devinity.org/threads/weapon-ideas-additional-shotguns.3224/
___________________________

**Shotguns worth considering (for now + later):**
- [ ] Double Barrel
- [ ] Beretta Perennia SV10
- [ ] Winchester Super X3
- [ ] Tactical M500
- [ ] AA-12
- [ ] "Boomstick"

**Comment by Donkie** [comment]
Keep in mind when the new wep update comes around they will all use the same weapon base and might not appear as they do in the add-ons you link.

**Comment by DawsonDevinity** [comment]
There's a new weapon update coming soon via Garry's Mod update, or just an update by TFA and combined?

**Comment by Donkie** [comment]
you misunderstood me.

In the event that I or Bayrock code a new weapon update. (we don't have any planned yet)

**Comment by DawsonDevinity** [comment]
I see, now.

Well, at the very least if you or someone could check off the stuff in the above boxes that of _possible_ interest, I'd much appreciate that.

**Comment by DawsonDevinity** [comment]
@Donkie — I would really mean a lot to me if you could perform the simple request of check marking the weapon ideas that interest you the most for now.  I am NOT telling you to work on them; it WILL however, help me come up with better content for you and Bayrock and everyone else.

**Comment by Donkie** [comment]
This week has been really stressful for me with school and stuff, I've been feeling physical effects from it.

I think all your weapon ideas are good, I don't care how they perform, that's all up to you guys, I mostly care about filesizes and ease of implementing. Where the latter will be the best if they're all from the same gun pack.

**Comment by bayrock** [comment]
@DawsonDevinity It's hard to predict the future. It really depends on the interest of the community and whether me or Donkie find time or motive to do it.

**Comment by DawsonDevinity** [comment]
It still should stop anyone from being able to checkmark blocks.  It takess like five (5) seconds to do....

Better yet, I'll just get feedback from the remaining body and go from there.
