### ISSUE TITLE
Some VERY weird errors.

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#188]
@Donkie I was looking through the console logs and some weird things are happening. It's throwing an error for this player for starwarsrp? 

`[X_123Connor123_X|49|STEAM_0:1:186358858] Lua Error:
[ERROR] gamemodes/starwarsrp/gamemode/config/config.lua:166: attempt to index field 'config' (a nil value)
1. unknown - gamemodes/starwarsrp/gamemode/config/config.lua:166
2. include - [C]:-1
3. unknown - gamemodes/starwarsrp/gamemode/cl_init.lua:30
[X_123Connor123_X|49|STEAM_0:1:186358858] Lua Error:
[ERROR] addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:653: table index is nil
1. unknown - addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:653
2. doInclude - [C]:-1
3. loadCustomDarkRPItems - gamemodes/starwarsrp/gamemode/libraries/modificationloader.lua:131
4. Call - gamemodes/starwarsrp/gamemode/libraries/modificationloader.lua:142
5. unknown - gamemodes/starwarsrp/gamemode/cl_init.lua:47
[X_123Connor123_X|49|STEAM_0:1:186358858] Lua Error:
[ERROR] A runtime error has occurred in "your jobs" on line -1.
The best help I can give you is this:
The category of "Clone Recruit" ("Recruits") does not exist!
Hints:
- Make sure the category is created with DarkRP.createCategory.
- The category name is case sensitive!
- Categories must be created before DarkRP finished loading.
The responsibility for this error lies with (the authors of) one (or more) of these files:
your jobs
------- End of Simplerr error -------
1. error - [C]:-1
2. unknown - gamemodes/starwarsrp/gamemode/libraries/simplerr.lua:467
3. error - gamemodes/starwarsrp/gamemode/libraries/fn.lua:82
4. mergeCategories - gamemodes/starwarsrp/gamemode/modules/base/sh_createitems.lua:1022
5. fn - gamemodes/starwarsrp/gamemode/modules/base/sh_createitems.lua:1041
6. Call - addons/ulib-master/lua/ulib/shared/hook.lua:109
7. Call - gamemodes/starwarsrp/gamemode/libraries/modificationloader.lua:143
8. unknown - gamemodes/starwarsrp/gamemode/cl_init.[X_123Connor123_X|49|STEAM_0:1:186358858] Lua Error:
Couldn't Load Init Script: 'starwarsrp/gamemode/cl_init.lua'
[X_123Connor123_X|49|STEAM_0:1:186358858] Lua Error:
[ERROR] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/cl_score.lua:207: SpawnableProps(models/props_borealis/bluebarrel001.mdl) is nil!
1. error - [C]:-1
2. unknown - gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/cl_score.lua:207`

**Comment by Donkie** [comment]
Yeah it's a bug, just ignore these.
