### ISSUE TITLE
[Minor] Limit Team Capacity to 1 player when <9 players.

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#19]
I don't think having a team with less than 9 players is really necessary. Players should be able to learn how to build a boat/defending by themselves without relying on a 2 man team ( or more ). This could somehow balance the advantages and disadvantages. (Like when 2 overpowered players team together and basically ruins the fun of other players.)

**Comment by Donkie** [comment]
Implementable but not sure about peoples opinions.

**Comment by CounterCraftz** [comment]
It's just irrelevant having teams with that low playercount. Maybe decrease it to >6 players?

**Comment by jeffreythe00** [comment]
@CounterCraftz Still a relevant issue? If so we should discuss it.

**Comment by CounterCraftz** [comment]
Gives unfair advantage. Another community has this system implemented already and it'd be nice to include it in as well.

To maintain team balance, if a team is full and the slots go down by one, it should kick the one who has recently joined.
