### ISSUE TITLE
Christmas shit*

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#194]
Santa Grigori - 40 tok [christmas drop]
models/jaanus/santa_hatless.mdl
models/weapons/c_arms_santaclaus.mdl

Obese Male - 60 tok [non-festive]
models/obese_male.mdl
c_arms_citizen.mdl

Christmas Miku - 125 tok
models/captainbigbutt/vocaloid/christmas_miku.mdl
models/captainbigbutt/vocaloid/c_arms/christmas_miku.mdl

Thanatos 150 tok [non-festive]
models/player/captainpawn/thanatos.mdl
models/weapons/c_thanatos_arms.mdl

**Comment by CounterCraftz** [comment]
will update content momentarily

**Comment by CounterCraftz** [comment]
👍

**Comment by DawsonDevinity** [comment]
Is there a way to make Thanatos' wings less jiggly?

**Comment by Donkie** [comment]
Yeah you can recompile the model with some tweaked jigglebone settings
