### ISSUE TITLE
Something wrong with snow on ground 

### ISSUE THREAD

**Issue by Applcore5** [GMDevinity/Flood#196]
Snow on ground is glitching, several players have reported it to be annoying them 

Instead of the snow just being constant, when players move and turn around the snow disappears when they look at certain parts of the map  (for some looking towards rooms theres no snow whereas looking at wall there is snow). Only appears to be happening to certain players, don't know what could be causing it. 
Perhaps we can make snow visuals optional (NOT FOR FALLING SNOW JUST THE SNOW ON THE FLOOR OF THE MAP)

**Comment by Donkie** [comment]
I noticed this while making it but thought I had fixed it. This happens only on specific locations in the map, so if you'd be able to find where I could probably fix it.
