### ISSUE TITLE
[PROP CONFIG.] Rename 'Other' to Miscellaneous

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#206]
Title speaks for itself.  The potential replacement name boasts a nicer ring, in my opinion.

**Comment by Donkie** [comment]
Categories aren't in the code anywhere, you can just change the string in the database and it should work.

**Comment by Donkie** [comment]
Also please don't assign me or bayrock to stuff, it's best to leave that to us

**Comment by DawsonDevinity** [comment]
Okay.

**Comment by DawsonDevinity** [comment]
Tried doing as you suggested (simply changing 'Other' to 'Miscellaneous') and this is what happened:

https://gyazo.com/69442ba25417e64bd23f97c062c50179

Instead of appearing below the Metals the entire grouping shifted up to the top of the tab without a title.
