### ISSUE TITLE
Fire Extinguisher bugged

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#207]
Two problems are up with the Fire Extinguisher:

- [x] While ammunition initially clocks in at 1,000 units, total depletion occurs at 250 instead of being at 0.  Not sure if max ammo is supposed to be 750.

- [x] Swapping weapons as soon as the Fire Extinguisher is momentarily depleted will remove the utility from the user's active inventory until the end of the round.

**Comment by Donkie** [comment]
Yet another weapon getting falsely removed from @bayrock s thing haha
