### ISSUE TITLE
Bugged Events

### ISSUE THREAD

**Issue by Zezuo** [GMDevinity/Flood#209]
Some of the events are currently bugged. People can abuse them to farm more money, while it happens, so... It would be better to fix them ASAP.

Known Issues:

Rope Event:

- [ ] Looks like Preparation stage is skipped at the start of the event.
- [ ] Water isn't rising at this event
- [ ] Battle stage happens "at shore", because of last mentioned issues.

Prop Roulette:

- [ ] Round starts immediately after "Round ending" stage is ended.
- [ ] Building stage is skipped at this event.
- [ ] Props that survived in the previous round will not disappear, and can be used in the Prop Roullete round again. (You don't need to re-buy them.)
- [ ] Winner of the round gets money spent on the props as a revard (not yet sure about that one.)
- [ ] Looks like players HP does not recovers back to 100, if they survived the round. 

Team Event:

- [ ] After the Team Event, Building stage is skipped.
- [ ] Props that survived in the previous round will not disappear, and can be used in the Prop Roullete round again. (You don't need to re-buy them.)
- [ ] Winner of the round gets money spent on the props as a revard (not yet sure about that one.)

I'll try to find more issues about the Events and update on the existing ones, if its possible.

**Comment by CounterCraftz** [comment]
This occurs in all events (including normal)

**Comment by Zezuo** [comment]
Well, if "some" evens have a slight chanse to bug out, These 3 (two, actually. Not intcluding Team one for now) are 100% bugged. 
Pirate Event, Random weps and others are fine, as long as I know.

**Comment by Donkie** [comment]
Fixed a few things that would cause many of these issues. I will close this and if any problems still exist please make a new issue.
