### ISSUE TITLE
Flood Prop Configuration (Up-to-Date Version)

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#21]
Configuration changes for Flood's props can be found in the link below:

https://docs.google.com/spreadsheets/d/1qnQdPJEqBHYD2aRqjmpnSf45Mfy_m3JY576ne8GSnH0/edit?usp=sharing

---

**OLD DOCUMENT:**
https://docs.google.com/document/d/1RdFkOED7JiqvZ6d6tCIihDcFmYhLJttOHBOqFak-7lI/edit?usp=sharin

**Comment by Donkie** [comment]
Can you mark applied changes somehow to this? So that I/we know what has been applied and not

**Comment by DawsonDevinity** [comment]
Would color coding work?

**Comment by DawsonDevinity** [comment]
Finished.  All props that have been reconfigured should be labeled with "UPDATED".

**Comment by DawsonDevinity** [comment]
More recalibrations have been pushed forward.  Please review when time is made available.

**Comment by DawsonDevinity** [comment]
New spreadsheet added.  Old version will be kept for archival purposes.
