### ISSUE TITLE
Edits to event description boxes

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#213]
Came up with revised versions of the description boxes that greet players whenever an Event plays.
_____________

**Pirate Event!**
- All boats can be boarded.
- Collect treasure chests!  Some contain goodies while others are rigged to explode!
- Attack players and boats with PvP weapons.
- Harpoons and extinguishers for everyone!
- Cannons are available for deployment.  Use them to cripple and tear apart ships.
- Boat motors and cannons are free!

_____________

**Haste Event!**
- Whoops, look at the time....  Start building!
- 1-minute Build Phase.
- Weapon and water damage damage is DOUBLED!

_____________

**Health Scramble Event!**
- The health values of all props have been randomly swapped! 
- Be careful with what you normally use to build boats….

______________

**One Weapon Event!**
- All players receive the same weapon during the Battle Phase.
- Weapon damage is DOUBLED!

______________

**Randomized Weapon Event!**
- All players receive the same weapon during the Battle Phase.
- Weapon damage is DOUBLED!

_______________

**Prop Roulette Event!**
- A random selection of props is only usable for the Build Phase!
- Your resourcefulness will be put to the test!

________________

**Zombie Event!**
- All players that die turn into wretched zombies!
- Gain moolah from harming humans as a zombie!
- Zombies can swim VERY fast—and even dolphin jump!

________________

**Tower Event!**
- Construct and tear down towers made out of non-buoyant props!
- Props do NOT unfreeze at the end of the Build Phase.
- Noclip is enabled server-wide.
- The Gravity Gun replaces the Physics Gun.

- How to build a tower:
(1) Spawn and grab a prop with the Gravity Gun’s secondary function.
(2) Adjust the prop’s orientation by moving your directional view.
(3) When desired, freeze the prop in place via secondary function again.
(4) Repeat steps 1–3 until a tower is built.

- Props can be unfrozen by pressing ‘USE’/'E' while looking at them.
- Noclip cannot be used while wrangling props at the same time.
- Be sure to build well above the water level depicted by the leftmost gauge.
- Water damage is DOUBLED.

________________

**Team Event!**
- All players are divided between two (2) gigantic teams!
- Use cooperation and teamwork to win.
- Prop limits are disabled.  Go crazy, but watch how much you spend!

_________________

**Juggernaut Event!**
- A bunch of sailors have been sent to subdue a party of fearsome, brutish Juggernauts.

- Juggernauts:
(1) Can only utilize the M249, AWP, Frag Grenade, Bazooka, and Harpoon Gun.
(2) All incoming water and weapon damage decreased by x0.75.
(3) Weapon damage output increased by x1.50.
(4) Do your best to get up close and personal.

- Sailors:
(1) All weapons and utilities are available at their disposal.
(2) Weapon damage output is x1.00.
(2) Incoming water damage is DOUBLED.
(3) Prop spawn limits proportional to number of Sailors vs. Juggernauts.
(4) Work together with teammates to defeat the Juggernauts.

**Comment by CounterCraftz** [comment]
You forgot the damage output for sailors

**Comment by DawsonDevinity** [comment]
Oh, you see, I didn't add that because the Juggernauts' already have a defense buff from sailor damage output.  ...Well, everything except for the Sledgehammer.

**Comment by CounterCraftz** [comment]
Ah, I was about to edit my comment; I was just making sure so it's retard-proof

**Comment by DawsonDevinity** [comment]
No worries. : )

**Comment by DawsonDevinity** [comment]
Added information about damage output of sailors.

**Comment by Donkie** [comment]
Done!
