### ISSUE TITLE
Remove glass ceiling from map.

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#218]
The glass ceiling has overstayed its welcome.  Not having it during the Christmas event was a lot better for a number of reasons, including being able to moderate from high above, avoiding prop teleporting, and being able to build taller building structures.  Plus it's just ugly looking; a memento from SSG's map, if you will.

**Comment by Donkie** [comment]
Was there any issues with it except for the tower event?

**Comment by DawsonDevinity** [comment]
Having the ceiling removed did not result in any serious issues.  The only thing players could do once it was gone was being able to walk on the walls that divide rooms via prop staircases. This could and has led to minor spying incidents.

We could always extend an invisible barrier above the walls that would impede players from standing on top of them.

**Comment by Donkie** [comment]
Added, also shouldn't be able to peek over the walls now.
