### ISSUE TITLE
Log family shared accounts & disguises to the server logs

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#226]
title

Both of these only print on the servercp except for the logs. It's a pretty neat tool for tracking down alternatives or to carry out moderation

FamilySharing: Viral | STEAM_0:0:159474911 has been lent Garry's Mod by STEAM_0:1:120757286

[prop] Viral (disquised as Selekt) spawned prop models/props_lab/blastdoor001c.mdl

**Comment by Donkie** [comment]
Wait so this is already getting printed?

**Comment by DrPitLazarus** [comment]
Cool. I think I'll add a notification on PlayerStats if the player has Garry's mod shared (lent to them).
