### ISSUE TITLE
Buoy floats halfway into water.  Fine-tuning possible?

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#23]
With its mass increased, the buoy will be rendered half-submerged in the water after stabilizing.

Q:  Would it be possible to tweak the prop's buoyancy (separately from the flotation categorical values) in such a way that it allow only the basal part to be half-submerged when unburdened?

http://images.akamai.steamusercontent.com/ugc/355024085895559739/3A44CEBEBB86B68444454CBC6093C6009E11D99A/

**Comment by Donkie** [comment]
Not possible.
