### ISSUE TITLE
Phase ends as soon as Fight begins on Pirate Event & Song issues + Other problems

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#232]
[//]: # (----Bug Template Info Start----)
[//]: # (Remove this section before posting. Remove this entire template if you're not reporting a bug)
[//]: # (!!!!Gather as much evidence as you can. There will often be a lua error somewhere,)
[//]: # (either in your console or in the server console, which can be reached using the ServerCP)
[//]: # (----Bug Template Info End----)

### Description of bug
Phase ends as soon as Fight begins on Pirate Event.

### What I expected to happen
Fight phase to carry out as normal

### What instead happened
Fight phase ended

### Steps to reproduce
* force pirate event
* setphase to flood

### Extra info (evidence, logs, etc)
http://images.akamai.steamusercontent.com/ugc/87093707062023956/6F0797A72B729AF31A11E2F11A8A47495D9886B8/

~~This only occurred once so I'm not sure if it can be reproduced again~~

also, 'regular' songs are being played on build phase even though it isn't ticked on pirate event

**Comment by CounterCraftz** [comment]
Event specific songs refuses to play
http://images.akamai.steamusercontent.com/ugc/87093707062098264/404EDF869FC94F735A72DDA9521982625DF3AD30/

http://images.akamai.steamusercontent.com/ugc/87093707062098382/001F93C8FDF21DC0EB3881818E2B37568B4D3554/

**Comment by DawsonDevinity** [comment]
The Tower Event is unplayable given the nature of the ceiling.  Props will still be vaporized once the Build Phase ends.

**Comment by Donkie** [comment]
Derp, forgot about that. Only fixed you not being able to go higher than the roof
