### ISSUE TITLE
[Sledgehammer] Tweaks

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#236]
- [ ] Hasten draw speed when equipped.
- [ ] Make thrown hammers capable of damaging players.

**Comment by Donkie** [comment]
So hammers should always damage players, then if players doesn't have any hammer they'll equip it?

**Comment by DawsonDevinity** [comment]
Yah, ideally player should be able to pick discarded hammers--whether or not they get hit by them.  Perhaps picking up hammers could made to work by pressing the USE key while looking at them.
