### ISSUE TITLE
[URGENT] Water adjustments

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#238]
- [ ] Adjust damage rate so that it is **-1 HP per 0.125 second**.

- [x] Lower depth at which a player must exceed in order to start being dealt damage.  
- As of the latest update, simply touching the water's surface will hurt players.
- The approximate depth at which water should start damaging players is indicated in the following image: https://gyazo.com/d230c23709be2b86ec73e1a5f399c531. Please refer to the **2nd model to the right**.

**Comment by Donkie** [comment]
-1HP per 0.25 second would result in only 4 DPS

**Comment by DawsonDevinity** [comment]
Oh, my bad.

Instead it should be -1 HP per 0.125 second.

**Comment by DawsonDevinity** [comment]
Okay, the depth for which water damage starts kicking in is too deep--we need to raise it more.

**Comment by Donkie** [comment]
It's either this or the previous.

**Comment by DawsonDevinity** [comment]
Well, the previous involved simply touching the water's surface.  I assumed it could be raised up by a tiny bit.  I need CounterCraftz to verify if he too agrees about the adjustments needed.

**Comment by Donkie** [comment]
Since I'm using the new method it won't be exactly as before. 
It's either touching or knees deep.

**Comment by Donkie** [comment]
Or back to old method

**Comment by DawsonDevinity** [comment]
Yeesh, nothing in between.  Well, let's see how it goes for now.

**Comment by DawsonDevinity** [comment]
Scrapping the new system in favor of the old.
