### ISSUE TITLE
Ideas for 'Mash-Up Events'

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#240]
The following are ideas for 'new' events that take elements from two different events and mash them together.
1. Prop Roulette + Health Scramble
2. Prop Roulette + Team
3. Prop Roulette + Rope
4. Team + Pirate
5. Team + Haste
6. Team + Tower

**Comment by Donkie** [comment]
Will require a huge amount of work to make possible, most likely won't be done.

**Comment by DawsonDevinity** [comment]
Lovely.
