### ISSUE TITLE
Random Loadout

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#241]
https://devinity.org/threads/random-loadout.2650/

**Comment by Donkie** [comment]
How is this different from the current randomweapons?

**Comment by DawsonDevinity** [comment]
No x2 damage.

**Comment by Donkie** [comment]
One weapon is literally one weapon. 
Random weapons is multiple weapons from different packs, just like you described here (but there is no titles to the packs)

**Comment by DawsonDevinity** [comment]
I see.  Welp, in that case we can salvage the loadout ideas and throw them into Random Weapons.
