### ISSUE TITLE
[RANDOM WEAPONS EVENT] Additional loadouts

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#242]
No need to add the names of the loadout sets to the game--they're only here for reference purposes.

___________________________
### Junkyard Scout
- AWP
- FiveSeveN
- Bugbait
- Frag Grenade
- Harpoon
- Fire Extinguisher
____________________________
### Scatterbrains
- SPAS-12
- Desert Eagle
- Frag Grenade
- Bugbait
- Harpoon
- Fire Extinguisher
____________________________
### Vietnam
- M16
- Five SeveN
- SPAS-12
- M249
- Grenades
- Bazooka
- Bugbait
- Harpoon
- Fire Extinguisher
____________________________
### The Middle East
- AK-47
- Galil
- Frag Grenade
- Sticky TNT
- Molotov Cocktail
- Harpoon
- Fire Extinguisher
____________________________
### Rule of Fours
- Golden Gun
- Harpoon
- Fire Extinguisher
____________________________
### BLASTula
- Bazooka
- Frag Grenade
- Sticky TNT
- Fire Extinguisher
- Harpoon
____________________________
### "Like _fire!_  _Hellfire!_"
- Molotov Cocktail
- Sledgehammer
- Crowbar
- Harpoon
____________________________
### Mortal Kombat
- Crowbar
- Sledgehammer
- Bugbait
- Harpoon
- Fire Extinguisher
____________________________
### Bolts and Arrows
- Crossbow
- Compound Bow
- Fire Extinguisher
- Harpoon
____________________________
### Ragnarok/Doomsday
- Predator Missile
- Sledgehammer
____________________________
### Shhh!
- TMP
- SVU
- Compound Bow
- Bugbait
- Sledgehammer
- Harpoon
- Fire Extinguisher
____________________________
### Mother-in-Law Russia
- AK-47
- SVU
- Frag Grenade
- Sledgehammer
- Harpoon
- Fire Extinguisher

**Comment by Donkie** [comment]
Implemented!
