### ISSUE TITLE
[WATER] Revert back to old damage system.

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#249]
It's really disappointing to say this, but, for better or worse, we need to go back to the old way of how water damage was handled.

It's just bizarre that the proclaimed .lua-coded water damage system can't even factor in depth.  Players can just hop across the water and avoid significant damage intake. Ridiculous, if not asinine.  : (

**Comment by Donkie** [comment]
It can factor in specific depth, it's just that I kinda want to use a pre-made function that tells me how deep the player is in water, to prevent having to calculate that myself, adding extra strain on the server.

**Comment by Donkie** [comment]
http://wiki.garrysmod.com/page/Entity/WaterLevel

**Comment by DawsonDevinity** [comment]
Okay, I see what you mean on the scope of keeping server stability.

---------------------

So, with the old system, are health point values completely static (in that they cannot be visually edited)?  I was thinking that perhaps a possible workaround could involve adapting the value/font readings and health to the damage system.

**Comment by DawsonDevinity** [comment]
Eh, it's sort of difficult to describe the concept to be honest.

**Comment by DawsonDevinity** [comment]
Okay, explained myself more clearly [hopefully].

**Comment by Donkie** [comment]
I can make the health bar more smooth, a lot of darkrp servers uses something similar.

**Comment by DawsonDevinity** [comment]
Let's give it a shot whenever you're up for it.  That could be our answer to solving the conundrum.

**Comment by Donkie** [comment]
![](http://f.donkie.co/BHiTQ)

**Comment by Donkie** [comment]
If the offset needs changing, tell me here pls

**Comment by DawsonDevinity** [comment]
It's still too shallow.  Try setting it to 6 units and see where that takes us.

Would it also be possible to configure the damage rate so that it's -1 HP per 0.125 seconds?
