### ISSUE TITLE
ShareX not returning correct image URL

### ISSUE THREAD

**Issue by DrPitLazarus** [GMDevinity/Flood#250]
[//]: # (----Bug Template Info Start----)
[//]: # (Remove this section before posting. Remove this entire template if you're not reporting a bug)
[//]: # (!!!!Gather as much evidence as you can. There will often be a lua error somewhere,)
[//]: # (either in your console or in the server console, which can be reached using the ServerCP)
[//]: # (----Bug Template Info End----)

### Description of bug
When uploading any file or screenshot with ShareX, it returns an invalid URL to image.

### What I expected to happen
The image URL would be something like `http://f.devinity.org/q28TFK`.

### What instead happened
The image URL is always `https://devinity.org/sharex.php`.

### Steps to reproduce
- Screenshot something.
- Make sure it uploads to the `Devinity.org` destination.
- Paste URL into browser.

### Extra info (evidence, logs, etc)
None.

**Comment by CounterCraftz** [comment]
I thought I was the only one that had the issue. Is it probably because of the switch to https (SSL)?

**Comment by DrPitLazarus** [comment]
Oh yeah. Forgot about that. 
Go to sharex destination settings, custom uploaders, make the post request to https, and then click one of those tests (set it to devinity) to save I think.

**Comment by Donkie** [comment]
Oh nice find pit!

**Comment by bayrock** [comment]
@jeffreythe00 Probably had this issue too.

**Comment by Donkie** [comment]
Can't fix this globally, you need to do what Pit said.
