### ISSUE TITLE
[CROWBAR] Replacement + Functionality edits

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#252]
**Replacement:**

- http://steamcommunity.com/sharedfiles/filedetails/?id=155266308&searchtext=crowbar

Not only is it in SWep form, but it can also be thrown (and retrieved).
___________________________

**Functionality Edits (if replacement is taken into consideration):**

- [ ] Configure the Crowbar so that it can be used to damage players outside of Pirate Events.
- [ ] When used against players, configure damage so that each hit takes off -3 HP.
- [ ] When used against props, configure damage so that each hit takes off -12 HP.*

*Sledgehammer damage directed towards props should be increased to -40 HP (?) as well.
____________________________

The above considerations would make a better and more viable weapon out of the crowbar.

**Comment by Donkie** [comment]
Did I manage to replicate the HL2 crowbar so good in lua that you didn't even know it actually was already in SWEP form? haha

**Comment by DawsonDevinity** [comment]
I think so!  👍
