### ISSUE TITLE
New loadouts for Random Weapons Event missing (?)

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#255]
Went ahead and performed some proof-checking, but only came across the following 'classes':

Class 1:
- Bazooka
- Frag Grenade

Class 2:
- AWP
- SVU
- Compound Bow

Class 3:
- _All submachine guns and rifles_

Class 4:
- All handguns.

Class 5:
- All weapons

**Comment by Donkie** [comment]
I most likely never pushed the update

**Comment by DawsonDevinity** [comment]
ohhhhh, silly me XP
