### ISSUE TITLE
Community Content Pack 1-3 switcharoo

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#257]
Counter wanted to add additional content to the existing workshop download packs, but he discovered that they were acting up.  We're not sure if it's because of memory capacity or something else, but they can't be edited.  Because of this, Counter went ahead and devised brand new content packs to replace them.

http://steamcommunity.com/sharedfiles/filedetails/?id=860037109&searchtext=devinity
http://steamcommunity.com/sharedfiles/filedetails/?id=860037377&searchtext=devinity
http://steamcommunity.com/sharedfiles/filedetails/?id=860327220&searchtext=devinity

Indeed, it is of major inconvenience that the malfunctions occurred (and we apologize in advance).  Could we look into incorporating the newer content packs into the server?

**Comment by Donkie** [comment]
Sounds weird. I'll get to adding these soon

**Comment by DawsonDevinity** [comment]
Could we try to work the replacement packs in sometime later this week?

**Comment by Donkie** [comment]
Yes, I've meant to do it yesterday but I've been pretty ill so haven't been able to.

**Comment by DawsonDevinity** [comment]
Ah, I'm sorry to hear about your illness--quite a few people over where I am are coming down with something too.  I hope you feel better sooner or later
