### ISSUE TITLE
Sledgehammers are thrown at an upward angle when aimed at props + players

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#259]
### Description of bug
The flight path of projectile sledgehammers do not match up to their users' cross-hair orientation.  This is most apparent when aiming at props and players.

### What I expected to happen
I expected thrown sledgehammers to travel and hit what I am looking at.

### What instead happened
The sledgehammer veered slightly upwards, missing the target by a variable degree depending on distance.

### Steps to reproduce
* Look at wall/player/prop from afar.
* Throw sledgehammer.

### Extra info (evidence, logs, etc)
- https://gyazo.com/915247cb03a11531c2374f8ba9f5eb39
- https://gyazo.com/5415180f9a08df03527f2b9cd3b24f19

**Comment by DawsonDevinity** [comment]
Apologies:  Providing screenshots.

**Comment by DawsonDevinity** [comment]
What's so confusing?

**Comment by Donkie** [comment]
It was a reaction emoji, calm down. It's confusing because there's no code that would do this.

**Comment by Donkie** [comment]
Fixed
