### ISSUE TITLE
Flood Economy – Fix-up decision

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#264]
I've put a lot of thought into it, and decided that the credit idea would likely be the best approach to take for stabilizing the Flood economy.  If implemented, we could also do away with the "!give #### ###$" command since there'd be no chance for money to be lost.

As emphasized, players could build whatever they'd want to.  However to gain funds, they'd have to top off their building expenses.

**Comment by RicksBeehive** [comment]
This'd be nice. It'd encourage proper building instead of the terrible "Tiny Boat + Grenades" tactic that occurs sometimes. Which generally makes a lot more money than building a proper boat.

**Comment by Donkie** [comment]
I don't think you're fully on track on what this specific issue is about @RicksBeehive

Anyway we decided that this was a bad idea
