### ISSUE TITLE
Additional Lamp Textures

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#27]
I have created a list of new lamp textures that could be looked into.  This has been long forgotten on the forums.  All information and links are stated in the following document.

https://docs.google.com/document/d/1TZ_ZghKA_CLbFIgKC9mn2Gc_ii_SzLLyiVanis3ECSo/edit?usp=sharing

**Comment by DawsonDevinity** [comment]
Nothing...?

**Comment by Donkie** [comment]
There is no reason to bump.

**Comment by Donkie** [comment]
Why was this closed
