### ISSUE TITLE
Equipped utility cannot be switched when 'Hide HUD' is enabled

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#275]
[//]: # (----Bug Template Info Start----)
[//]: # (Remove this section before posting. Remove this entire template if you're not reporting a bug)
[//]: # (!!!!Gather as much evidence as you can. There will often be a lua error somewhere,)
[//]: # (either in your console or in the server console, which can be reached using the ServerCP)
[//]: # (----Bug Template Info End----)

### Description of bug
Pressing '1'/Scrolling does not swap out the Physics Gun for the Tool Gun (and vice-versa) during Build Phase.

### What I expected to happen
I expect boatmotors to propel the boat forward

### What instead happened
I expected equipment to switch out....

### Steps to reproduce
1. Enable 'Hide HUD' via Settings
2. Try switching weapons.

### Extra info (evidence, logs, etc)
No console errors.  Nothing.

**Comment by Donkie** [comment]
Can only be fixed by allowing the weapon selection HUD

**Comment by DawsonDevinity** [comment]
Oh.
