### ISSUE TITLE
Lamp and Light Tools:  Value Range Recalibrations

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#28]
Another long-forgotten idea from the forums:  Curtail the value ranges for the lamp and light tools.  Details can be found within the following link:

https://docs.google.com/document/d/1IaFgDSn31FGfNg4mhsNwITKIud8yFKVwcZ-R7LaDQ5o/edit?usp=sharing

**Comment by Donkie** [comment]
this is done already
