### ISSUE TITLE
Other physmats entries are not saved when prop config is updated

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#283]
### Description of bug
Physmats entries such as "plastic_barrel_buoyant," "plastic," and "snow" cannot be saved to the prop config.

### What I expected to happen
I expected them to save...

### What instead happened
The cell entry was left blank after updating.

### Steps to reproduce
*Type "plastic," for example.
*Update.

### Extra info (evidence, logs, etc)
N/A.

_______________________________

If it turns out that nothing can be done to update allowed physmats (preferably make ALL of them accessible), could I get a list of physmats that do work?

**Comment by DrPitLazarus** [comment]
By viewing the structure of the table, I found that the selectable values for physmat are `'metal_bouncy','metal','dirt','slipperyslime','wood','glass','concrete_block','ice','rubber','paper','zombieflesh','gmod_ice','gmod_bouncy'`.

**Comment by Donkie** [comment]
Yeah look at the table structure. The ones listed there are the ones available. @DawsonDevinity
