### ISSUE TITLE
Um

### ISSUE THREAD

**Issue by firedraft** [GMDevinity/Flood#29]
@DecapX So I being retarded like the usual and spam poked someone on TS. Decap banned me on the forums and TS. Even IP banned me on the forums. So I can't even view it. 
I'd like to say, that I should be able to appeal this ban on the forums but he is giving me no chance to do so. I feel his personal grudge between us is getting in his head as an admin. I'd like to be unIP banned and unbanned from the forums.

**Comment by firedraft** [comment]
I will go back to old Firedraft If I get unbanned on TS.

**Comment by CounterCraftz** [comment]
k

**Comment by DecapX** [comment]
nah
