### ISSUE TITLE
Active lamps [horribly] glitch out textures on map walls

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#294]
### Description of bug
Lamps that are made to shine light onto a certain part of the map will cause its textures to horribly glitch out.
- Issue is independent of lamps' FOV + brightness.
- The smaller the light distance, the lower the chances of the glitch occurring.
- Textures return to normal for the client when he/she exits and returns to the affected server.
- All lamp textures cause the glitch.
- Has been ongoing for more than a year without explanation.

### What I expected to happen
I expected the lamp to not cause any map fuckery when active.

### What instead happened
The map's textures whack out when a lamp is spawned and shined in the wrong place.

### Steps to reproduce
* Spawn a lamp.
* Shine it against one of the main walls.

### Extra info (evidence, logs, etc)
https://gyazo.com/598251833021056bc2c11421ea7cf49b
https://gyazo.com/3fdc6216daa346a51c245b5a806f3761
https://gyazo.com/f42ef2c09c3e20abd9c7b42bdceafd17

**Comment by Donkie** [comment]
Never witnessed, most likely a issue with your graphics card or drivers. Definitely not something I can fix atleast.

**Comment by DawsonDevinity** [comment]
Well, I'll need more feedback from others.

I can certainly say that on my end it has to do with the ineptness of OS X.

**Comment by DawsonDevinity** [comment]
Likely has to do with just graphics card capacity.  Closing.
