### ISSUE TITLE
April 1st edits to Flood

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#308]
Ideas for now:
- All players turn into Obese Male.
- Paper towel roll mass change . . . . . . 160 to 10,000
- Edit Healing Stick so that it takes away health (i.e., -20 HP).
- Speed up sledgehammer projectiles from x1.0 to x5.0.
- Edit USP so that it can inflict player damage (i.e., -0.5 HP).
- Zombie Event . . . . . Humans start as zombies, but turn into humans when killed.
- Juggernaut Event . . . . . Sailors are juggernauts, while juggernauts are sailors.
- Haste Event. . . . . . Reduce Build Phase time to 25 seconds.
-  Build to Top. . . . . . Enable low gravity.
- Team Event . . . . . Configure so that weapons can inflict damage.
- One Weapon Event . . . . . Raise Damage multiplier from x2.0 to x5.0.
- Pirate Event . . . . . Increase chest appearances by four-fold, but also rig non-booby-trapped chests to explode.
- Prop Roulette Event . . . . . Further decrease available prop selections.
- Scramble Event . . . . . Health values are not revealed until the Build Phase ends.
- Predator Missiles . . . . . Reduce cost to $500, but shrink explosion size and reduce damage to -5 HP.
- Flood subphase (within Preparation)  . . . . . Allow weapons to be usable prior to Fight Phase.
- Boat motors . . . . . Propeller strength increased by x10.
- Zombies can utilize weapons (?).
_____
More on the way...

**Comment by Donkie** [comment]
These are great ideas and good effort from you but sadly I just realized I will be occupied the whole weekend and I won't have time to add and then remove these changes for April 1st.

Maybe @bayrock can do.

**Comment by DawsonDevinity** [comment]
Eh, while it wouldn't have the genuine feel of April Fools, we could always hold the occasion later.

**Comment by DawsonDevinity** [comment]
I assigned Bayrock for good measure.  This can be undone if it won't work out.
