### ISSUE TITLE
Threads that are posted in General Discussion "corrupt"

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#316]
### Description of bug
Threads that are posted in General Discussion "corrupt," in that further posts cannot be added to those affected.

### What I expected to happen
I expected posts to appear normally....

### What instead happened
This:  https://gyazo.com/6febec04afadda2b310a8293894f4265

### Steps to reproduce
* Create a thread in General Discussion
* Post several 'reserve posts' (was working on an elaborate discussion).
* Take time with editing, and then try to add another post.

### Extra info (evidence, logs, etc)
- https://xenforo.com/community/threads/xenforo_exception-cannot-insert-a-message-in-the-middle-of-a-discussion.100413/

**Comment by bayrock** [comment]
The steps to reproduce a bug are only valid if the bug can actually be reproduced.

I can't reproduce it, and it sounds like a one-off. Likely caused by a hiccup with the server (where we host the site) or somehow due to your rapid posting/editing.
