### ISSUE TITLE
Changes to Server Portal

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#32]
- [ ] Add live feed on how many players are on the server. (Similar to Forums)
- [ ] Prevent players from connecting to the same server that they are on to. (Maybe shade the current server that they are on to grey)
- [ ] Maybe add a player list (similar to gametracker) when right clicking to view server info.

**Comment by Donkie** [comment]
Good ideas

**Comment by CounterCraftz** [comment]
Concept:
https://i.gyazo.com/0ed6b5d12bae133d08981e7d8251872c.jpg

List will shorten if there is less players.

**Comment by Donkie** [comment]
Might add that this is more difficult than it seems like, but it's something I definitely want.

**Comment by CounterCraftz** [comment]
will revise this later on
