### ISSUE TITLE
Implement "auto-cleaving" to teams with too many players in them (when servers aren't populated enough)

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#39]
Devise a code--something--that would auto-cleave/ -abolish teams that have too many players in them during times when servers are not populated enough to warrant 3- or 4-member teams in the first place.

**Comment by DecapX** [comment]
Maybe a menu can come up for the team leader that asks them which team mate they would like to remove from the team. If they do not choose one in 30 seconds or close the menu, it will destroy the team.

**Comment by Donkie** [comment]
Most games would solve this by just kicking the last joined player. If I do the kicking after a round ends no boat issues will be brought up.
