### ISSUE TITLE
"So I've been told"

### ISSUE THREAD

**Issue by firedraft** [GMDevinity/Flood#40]
I have been informed I would have the chance of appealing my permanent and IP ban. I kinda believe It will get denied as soon as its posted. So to save me the effort, I'm just going to ask if I actually can. Before I spend a whole night typing and revising an appeal. 

Source: https://gyazo.com/acda010df98943c2f46eb53b721fee03
This was a few weeks back. Maybe 2-3.

**Comment by DoctorSilver** [comment]
No, Decap said he would wait a indefinite amount of time before he even thinks about unbanning you.

We tried to give you as many chances as we could, you're a complete trouble maker and seem to not have any intention of following any rules.  Why should we even think about letting someone back into a community if all they are is a huge troll who doesn't care about the rules?

**Comment by firedraft** [comment]
I would like Decap, Donkie, or Bayrock to make that decision. I request this to prevent any fighting and making myself look bad.

**Comment by DecapX** [comment]
There is literally nothing you can do to convince me you will change your behavior or your antics. I don't trust you and I don't want you back. That's my decision, if Donkie or Bayrock really want to they can override it.

**Comment by Donkie** [comment]
We gave you a full months ban as a warning that your behavior wasn't something we wanted. You didn't listen at all, so why would you've changed now? 
I'll give you at least  a few more months, and then you'll be able to make a ban appeal, if it's really good and genuine I might consider unbanning you.

**Comment by firedraft** [comment]
Alright sounds good! I'll be looking forward to it.
