### ISSUE TITLE
Materials "shader3" and "moneywrap" need to be removed.

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#49]
The following materials for the Material Tool ought to be removed because they promote unfair advantages concerning camouflage (i.e., props that are cloaked are rendered more difficult to track down by sight and damage).  When viewing cloaked props from afar, their health + ownership tags can get in the way, making them even more frustrating to deal with.

```
models/shadertest/shader3
models/props/cs_assault/moneywrap
```

**Screenshots to prove the point:**

"Shader3"

- http://images.akamai.steamusercontent.com/ugc/266086874799507049/4D0ADA899F34511BC3E644B3DA037C53D1E173D4/
- http://images.akamai.steamusercontent.com/ugc/266086874799521807/6631891236B9EDFA3E388B4C014C530C9E92377D/
- http://images.akamai.steamusercontent.com/ugc/266086874799565778/1561F2F47CF40A9BD4E58256ECC55848CF2F4B8C/

"Moneywrap"
- http://images.akamai.steamusercontent.com/ugc/266086874799516923/1B042912A46B97885F69E069429D4725D322BE2A/

**Comment by jeffreythe00** [comment]
#55
