### ISSUE TITLE
Alternative Feature  for Incognito

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#51]
Obviously, when I try to use incognito, players automatically reveal my name through the scoreboard (same level, days, etc.)

I have a suggestion in order to replace that issue:

- Ability to mimic a player's database (Avatar, Money, Playtime, Rank [donation status], Level, and Steam Profile via Scoreboard/Player Card, etc.)

When using !hide, it will automatically grab any user data entered. If a name is found, then it'll show a menu if staff wants to use that name w/ the database or customize/scramble a makeup one.

If that exact player is on and you're using their name, it'll prompt the staff member via chat to switch to a different name.

I know people can check the incognito staff easily but this will ease it up abit.

Mockup?
https://gyazo.com/87b118d2fb4e934d11c48a7978705cff

When using "Generate Random Data", it'll use the same name/avatar but with different level/days and status (rank)
Status ratio should be 35:65 (35 will give that person a random rank where 65 doesn't give donation status)
 
This might seem like a retarded idea but incognito should be more essential. Always feel free to change idrgaf.

**Comment by DawsonDevinity** [comment]
I would like add that this incognito addition should also generate a random value of cash that would go towards temporarily hiding the user's real amount.  Without it, anyone incognito that has a bajillion dollars would still be susceptible to being spotted + called out.
