### ISSUE TITLE
Spread out damage caused by water

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#52]
Right now water damage is a flat -4 HP per `*insert exact seconds*`.  It would be nice to see it broken up into smaller increments where the damage is -1 HP instead.  The time it would take to receive -4 HP would technically remain the same.

**Comment by DawsonDevinity** [comment]
Bump....

**Comment by Donkie** [comment]
Why? I still don't know if this is possible. It's even marked as low priority.

**Comment by DawsonDevinity** [comment]
If SSG can do it, so can we.  Besides, damage would be more forgiving if damage was partitioned into smaller portions.

**Comment by DawsonDevinity** [comment]
Apologies for reopening, but would it be possible to adjust the water damage so that it proceeds as -1 HP per 0.25 second?
