### ISSUE TITLE
Display "Mass" information for props in-game.

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#53]
Description is self-explanatory.  Add an information field for prop mass in-game.  Doing this would allow players to provide feedback and possibly suggestions for prop re-balancing/ improvement.

**Comment by Donkie** [comment]
It's a good idea but it kinda falls into the "too much information" bucket. A regular player doesn't give a crap about the exact value of mass, however how well it floats is a better information, which is something we already got.
