### ISSUE TITLE
Flood 2.0 Testing

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/Flood#54]
Some testing notes.

Things needed to be tested:
- [ ] Items 2.0, store, events overriding, zombie event
- [x] All 3 new grenades need balancing
- [x] New prop protection system ( props don't immediately vanish upon leaving now. Will help people who often disconnect. This will also prevent teams losing half their boat during fight etc.)
- [x] HL2 weapons: revolver, smg, pistol, ar2 and crowbar
- [x] Bayrock's new hints
- [x] Weld tool distance limit
- [x] !bans command

Post relevant things we agreed upon in here that needs changing

**Comment by CounterCraftz** [comment]
add another setting to "Reset all Filters" just incase if someone fucks up somehow

**Comment by Donkie** [comment]
joining players doesn't see existing players accessories

**Comment by CounterCraftz** [comment]
swap controls on shop(preview to right, customizing to left)

**Comment by CounterCraftz** [comment]
add money packs to misc, forgot that ;p or add a completely new category

**Comment by CounterCraftz** [comment]
instead of adding 1,5,10,20 money packs, add another button somewhere to buy packs at a custom value similar to Q>Tokens where you buy tokens for money

**Comment by Donkie** [comment]
Crowbar needs recoding

**Comment by Donkie** [comment]
HL2 weapon splashes are huge
