### ISSUE TITLE
Materials to remove

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#55]
Materials to be removed:
models/props/cs_assault/moneywrap
models/shadertest/shader3
models/props_combine/tprings_globe ^
models/shadertest/shader4 ^
models/props_c17/frostedglass_01a ^
^debatable
Honestly, any type of material that is somewhat transparent needs to go so rule 17 can go fuck itself

**Comment by jeffreythe00** [comment]
@Donkie can we have this implemented with 2.0?
