### ISSUE TITLE
Add ULX feature to Flood

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#56]
We used to have a feature where I could type !cflist donkie and it would say something like (Donkie is friends with ( Bayrock, Jeffreythe00, CounterCraftz ) but only if those players were also on the server.

I'm pretty sure this feature I'm requesting was in the ULX extended script Bayrock got on coderhire, the one that got leaked. I "may" still have a copy but I highly doubt it.

I would like this feature added because when there are a bunch of trolls. I can keep a closer eye on them all.

-------------------------------------------------------------------------------------------------------------------

P.S

It would also be really amazing if when an admin runs the command, it would run the command on all servers and send that data to the admin who queued the command. 

IE:
!cflist donkie

Donkie is friends with:

US 1: Jeffreythe00, 
US 2: Donkie
EU 2: Bayrock, CounterCraftz

**Comment by Donkie** [comment]
First idea: very good, please try to dig up that script if you can.

Second idea about interserver stuff, not atm.

**Comment by jeffreythe00** [comment]
I remembered I never actually had a copy of the script. Maybe on an old HDD with a copy of an old version of flood. Maybe not though.

However I looked around and found a copy on leakforums. The author claims there is no backdoors but I can't verify this. Just want to be honest :p:. If interested link below.

https://mega.nz/#!YhAU2QqD!I9RzqWKFNBgvrPDYme-1el2tkTHv7fUofFtuoqJTWbw

**Comment by Donkie** [comment]
That lua file contains no such feature

**Comment by Donkie** [comment]
Coded by @bayrock 
Not live yet though. Probably 2.0
