### ISSUE TITLE
Improve !hide

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#57]
The !hide feature is a great function and is extremely useful.

However it has a major flaw. Let me show you.

Suggestions are:

- Randomize the playerlevel when !hide is issued with a set variable. Something like 1-85 (too high and it will draw attention which is what we're trying to avoid).
- Randomize cash value (I realize there can be huge issues with abuse here and we need to be careful. Perhaps only allow them to buy props while in !hide)
- Randomize playtime

![hl2_2016-07-08_16-21-17](https://cloud.githubusercontent.com/assets/6297372/16701277/bdfec826-452c-11e6-8438-8c5bc0817c94.jpg)

**Comment by Donkie** [comment]
Yeah I know its abit broken. It's a really shitty system atm, but I'll try to do these.
