### ISSUE TITLE
MOTD Revision Request

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#58]
Change the highlighted text to (Hope you like it :dango: ): **(Go solo or make a team. Nothing in between)**

![hl2_2016-07-08_21-49-41](https://cloud.githubusercontent.com/assets/6297372/16705387/75e20998-4556-11e6-82d7-f3df010a423a.png)

**Comment by jeffreythe00** [comment]
All yay or nay?

**Comment by Donkie** [comment]
Motivate?

**Comment by jeffreythe00** [comment]
Wat?

**Comment by Donkie** [comment]
Why would you want this change, I don't see how either the old or new could be any different in confusion

**Comment by jeffreythe00** [comment]
I'm always looking for ways to improve the rules, game ect. This seemed to me like it would be a little easier to understand and is a bit catchy. If nobody else agrees, then that is ok.

**Comment by CounterCraftz** [comment]
Just hit me up on the revision and i'll edit op

**Comment by Donkie** [comment]
Any status on this?

**Comment by jeffreythe00** [comment]
Oh. Sorry. Forgot to close.
