### ISSUE TITLE
1st 3 phases on /roundstats being included(Time Alive)

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#62]
After round is over, time alive is including build, get on and prep instead of only fight. Adds up to 9:20 if survived the fight phase. (instead of 4:40) Inaccurate results

**Comment by CounterCraftz** [comment]
Reference: https://i.gyazo.com/84ffca16134e40b2022dafa4ca6b010e.png

Fight Phase doesn't last <6 min

**Comment by Donkie** [comment]
This has been fixed
