### ISSUE TITLE
Unwelded props not being refunded

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#63]
Title

even if you place a single prop down, no refund. can be troubling because you can just ez cashgrab without any type of creativity at all

**Comment by Donkie** [comment]
how can it be cashgrab if you don't get any refund, I'm confused

**Comment by CounterCraftz** [comment]
If you just spawn a single prop, it kinda defeats the purpose of "building a boat". (By default you need to have at least 2 props in order to not have it removed by the system.)
