### ISSUE TITLE
I can't join teamspeak

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#67]
I can't connect to ts.devinity.org. 

http://imgur.com/a/ixkxh

**Comment by DrPitLazarus** [comment]
Don't use https.

**Comment by jeffreythe00** [comment]
http://imgur.com/a/CceTS

**Comment by jeffreythe00** [comment]
Nevermind. "Devinity" was spelled wrong in my bookmark settings for some reason.
