### ISSUE TITLE
List of people who need TS3 ranks re-given.

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#68]
People have lost their Ts3 perms because of windows re-install. Heres a list of people who need their ranks back.

@Donkie 
@DecapX 
@bayrock 

Jeffreythe00       | Admin   | STEAM_0:0:29495527  | http://devinity.org/members/jeffreythe00.5/
CounterCraftz     | Admin  | STEAM_0:0:8599803    | http://devinity.org/members/countercraftz.929/
Seth                    |  Jr Mod | STEAM_0:0:93433914 | http://devinity.org/members/seth.5617/
Wolfgang           | Jr Mod  | STEAM_0:1:94389816  | http://devinity.org/members/wolfgang.1275/
Noriaki Cocaine  | Jr Mod |  STEAM_0:1:28895944 | http://devinity.org/members/noriaki-cocaine.1397/
Bayrock              | Founder| STEAM_0:0:24609909 | http://steamcommunity.com/id/bayrock/
ArrayZ_LSD        | Jr Mod   | STEAM_0:1:75694437 | http://devinity.org/members/arrayz_lsd.2197/
Logster004        | Jr Mod | STEAM_0:0:94152063 | http://devinity.org/members/%E2%98%9C%E2%98%86%E2%98%9Elogster004%E2%98%9C%E2%98%86%E2%98%9E.3939/

**Comment by CounterCraftz** [comment]
my rank was gone due to reinstallation of teamspeak and my identity key being wiped

**Comment by jeffreythe00** [comment]
Same as counter

**Comment by Donkie** [comment]
You guys gotta remember to back up your identity keys. Are any of these resolved?

**Comment by jeffreythe00** [comment]
As far as I'm aware, no they have not been,
