### ISSUE TITLE
Shoutbox and double posting

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#69]
I realized what is causing the double posts you see in the shoutbox. 

Looks like any time there is a post in a thread which needs approval, the system thinks your reply is a new thread instead of a new post. So it then announces that a new thread has been created in the shoutbox.

![chrome_2016-07-27_14-22-41](https://cloud.githubusercontent.com/assets/6297372/17187282/994fcbcc-5406-11e6-84ec-26cba0d79dbe.png)

**Comment by bayrock** [comment]
It's also any post that's made in the thread before it gets approved. So, if other mods reply it will spam the shoutbox more than once.

**Comment by bayrock** [comment]
I got a prime example of the statement I just made:
![prime_example](https://cloud.githubusercontent.com/assets/6297381/17212935/df768a16-549f-11e6-894c-a423ce92e6d1.png)

@Donkie @jeffreythe00

**Comment by Donkie** [comment]
>still uses devinity dark when we have devinity green

**Comment by bayrock** [comment]
I always hated the Devinity green style, lol.

**Comment by Donkie** [comment]
Can't we just remove shoutbox reporting for ban request forum

**Comment by jeffreythe00** [comment]
^ fine with me.

**Comment by bayrock** [comment]
We can but the original idea was this would keep the mods on their toes with requests.

**Comment by Donkie** [comment]
Posting shit that's trivial to half of our forum users in the shout box feels pretty unnecessary. As said, watching the forum would give you an email instead.

**Comment by bayrock** [comment]
Alright,  sounds good.
