### ISSUE TITLE
NDA writing 

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/Flood#70]
We need some clear guidelines of what staff is allowed to tell the public and ranks below them. 

Either we make a new thread stating all areas of non disclosure, or we edit each thread in mod forums and add on to them. 

I'm thinking something along this:
* Slack: You're not allowed to mention, hint at, screenshot or talk about anything said in a private slack channel to anyone not included in that channel. 
* Forum: Same shit for PMs and forum boards 
* Server Testing: Any new feature shown while testing the gamemode on a private session can not be talked about outside to people not included in the testing event. 

Any of these can be overridden on a per-case basis by an Admin or higher authority. They can decide if it's okay to "leak" something.

**Comment by jeffreythe00** [comment]
Yeah, I agree. Have somebody of the same rank or higher review the info and get permission for said leak.

**Comment by DrPitLazarus** [comment]
Sure. 
>Thanks for assigning this to me twice, Donk. ;)

**Comment by Donkie** [comment]
I can do it again if you want.

**Comment by jeffreythe00** [comment]
All current Mod+ has been added to a conversation about this.

**Comment by Donkie** [comment]
Conversations dissappear. This needs to be put in a thread.

**Comment by jeffreythe00** [comment]
http://devinity.org/threads/dont-be-a-leaker.3384/#post-28133

**Comment by jeffreythe00** [comment]
@donkie I'm closing this. If you need me to add anything else related to this feel free to reopen it and let me know what you need.
