### ISSUE TITLE
Content does not automatically download

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/Flood#73]
The workshop content doesn't automatically download.

**Comment by Donkie** [comment]
?? It've always done this, no changes made

**Comment by bayrock** [comment]
@donkie if I'm not mistaken he's saying players are seeing a lot of content errors because it's never downloading for them

**Comment by jeffreythe00** [comment]
^This.

**Comment by jeffreythe00** [comment]
I can confirm it is not downloading because when I re-installed windows, I had to manually sub to it and a lot of other players have asked me where they can get the textures from ingame.

**Comment by Donkie** [comment]
Fixed?
