### ISSUE TITLE
Remove "Easy Weld"

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#77]
Can be used to crash the server if they spawn and weld props that has gaps on it + easily defeats the purpose on BTTP event

**Comment by jeffreythe00** [comment]
All of these issues are solved in 2.0 with Donkies implementation of the area weld.

**Comment by Donkie** [comment]
Not really, Jeff. Can you show me how reproduce this some day, counter?

**Comment by CounterCraftz** [comment]
I can't replicate it for sure but have banned 2 individuals a few weeks ago with models/props_phx/construct/windows/window_curve90x2.mdl. (I'll try atleast)

**Comment by jeffreythe00** [comment]
Pretty sure I can replicate it. I'll have to do testing though.

**Comment by CounterCraftz** [comment]
I just did it

**Comment by jeffreythe00** [comment]
Can you do it with normal weld too?

**Comment by CounterCraftz** [comment]
no, just only right click feature

**Comment by CounterCraftz** [comment]
http://f.devinity.org/o0WiK1

**Comment by CounterCraftz** [comment]
https://slack-files.com/T0H7GJL7Q-F1Y4LMNMB-5cd5fb92d0

**Comment by jeffreythe00** [comment]
This is how I see it happening.

Server gets 28 people.
A few 4 person teams are created
Round ends, and a few people rage quit (I notice some people will leave if they die or lose a lot)
Several people leave, breaking those 4 person teams down
Some people get upset because their team is reduced to 3
some more people leave
teams are further reduced
domino effect.

**Comment by jeffreythe00** [comment]
I thought this was smart weld. My mistake. Continue on with your discussion. I agree with it.

**Comment by CounterCraftz** [comment]
https://youtu.be/21bzQ2bD6G0

**Comment by jeffreythe00** [comment]
Is this still something on the "to do" list?

**Comment by Donkie** [comment]
tbh I think easy weld is used enough to not warrant a removal because of this
