### ISSUE TITLE
Allow zombies to apply force to/unweld player props

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#84]
title

**Comment by DawsonDevinity** [comment]
Sounds like a interesting feature to add.  The only issue I see coming out of this would be that the zombies could just remain underwater and dismantle the boats.  They wouldn't have to engage humans directly, meaning that they'd also be extremely difficult to kill without resurfacing.

**Comment by CounterCraftz** [comment]
Zombies cannot melee underwater
