### ISSUE TITLE
Allow players to mix and match grenade-type weapons

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#86]
As a replacement to the current setup, players should be able to customize their loadouts for grenade-type weapons.  By default, a total of six (6) empty equip slots would be assigned.  From there it would be up to the user to decide how much of what they'd like to bring with them into fights.  Some may prefer just having Molotovs while others might go for a sampling of different things.

This should be taken into consideration after 2.0.

**Comment by Donkie** [comment]
Could be integrated with the load out system somehow #221

**Comment by DawsonDevinity** [comment]
If we could allow players to customize grenade/bomb inventory quantities, we should move towards further balancing the frag grenades, sticky TNT, and molotovs.
