### ISSUE TITLE
Special prop for post 2.0 - Treasure Chest

### ISSUE THREAD

**Issue by DawsonDevinity** [GMDevinity/Flood#87]
Synopsis:

- A heavy, high-health wooden prop that sinks, but releases goodies when destroyed by the user or other opponents.

http://devinity.org/threads/wooden-prop-idea-treasure-chest.2445/

Content is subject to modification.

**Comment by Donkie** [comment]
Would be too similar to the current piratechest and cause unneccessary confusion
