### ISSUE TITLE
Clientside bug in regards to Teams

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/Flood#94]
https://gyazo.com/7b505a66b811281d62f0c66d3e2658ee
https://gyazo.com/879a779653019a2f3505c0cdb55af7c2
https://gyazo.com/8eb6cfe374498cc6d6a75930c3e559ae

https://gyazo.com/bba8d521715b6b5cf7d1153ac1e668af
https://gyazo.com/6d2a6a9a24c0d98e1251dd5d5355b663
https://gyazo.com/26359fb17ca672c59171c324480b6d58
https://gyazo.com/d750365803cd2251774d90179b028c62

Really annoying

**Comment by Donkie** [comment]
Fixed
